name: spotifyclone
description: spotify clone made with Flutter, BLoC and firebase
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1

  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  meta: ^1.3.0
  very_good_analysis: ^2.3.0
  lint: ^1.8.2

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter

  mocktail: ^0.2.0

  flutter_native_splash: ^2.0.4

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo_small.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GothamMedium
      fonts:
        - asset: assets/fonts/GothamMedium.ttf

